pipeline {
	agent { label 'slave2' }
  
  triggers {
        pollSCM '* * * * *'
  }

  tools {
    maven 'maven-3.9.2' 
  } 
  stages {
    stage ('Build') {
      steps {
        sh '''
        	cd ./maven/simple-war/ 
          cat ./src/main/webapp/index.jsp
        	mvn clean package
        	cd ./target/
        	ls
           '''
      }
    }
    stage ('Deploy') {
      steps {
        script {
           deploy adapters: [tomcat9(credentialsId: 'tomcat_deploy', 
	   path: '', url: 'http://43.205.232.222:8080/')], 
	   contextPath: 'itdefined-war-1.0.0',
	   war: 'maven/simple-war/target/itdefined-war-1.0.0.war'
        }
      }
    }
  }
}
